### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by dsibiski** [harshadabhanose/trivia-game#1]
Hi @harshadabhanose,

I'm trying to run the app but not having success. Please see the screenshot below. If you're able, please update the Readme with correct instructions or submit a fix to the repository.

Thanks!

![screenshot 2018-06-06 21 11 59](https://user-images.githubusercontent.com/2922932/41072926-a987604c-69ce-11e8-877e-11466af87156.png)

**Comment by harshadabhanose** [comment]
Hello Dave,

I had missed to include the step in readme for `react-native update`. I didn't push the iOS folder from the template to avoid the bulky repo. So we have to do upgrade to create the missing folders and files. I have updated ReadMe file now. Please check and confirm back.

Harshada

**Comment by dsibiski** [comment]
@harshadabhanose Thanks, it's working now!
